### ISSUE TITLE
Where to get annotations for deepfashion(consumer_to_shop)? 

### ISSUE THREAD

**Issue by weiwang0728** [mikwieczorek/centroids-reid#10]

**Comment by vicchu** [comment]
This work is really good,  
I also meet the same problem, may you please offer me the coco formate JSON file of Deepfashion you used.
Many thanks. @mikwieczorek

**Comment by mikwieczorek** [comment]
Thanks for your interest in our work. I will prepare the script to transform fashion datasets annotation to Coco-format in a couple of days.

**Comment by vicchu** [comment]
> 

It will be great,  Thank you!

**Comment by vicchu** [comment]
> Thanks for your interest in our work. I will prepare the script to transform fashion datasets annotation to Coco-format in a couple of days.

It will be great, Thank you!

**Comment by weiwang0728** [comment]
I would like to reproduce the results in your paper, but I can't get the annotations of the fashion dataset into Coco format, can you share the script? I would really appreciate it.

**Comment by mikwieczorek** [comment]
Yes, I will release the script in coming days.

**Comment by weiwang0728** [comment]
Can you provide the script to convert the annotations of the fashion dataset to Coco format, thank you very much for your work.

**Comment by mikwieczorek** [comment]
Added `scripts` folder than contains code necessary to transform raw dasets to coco-reid format
