### ISSUE TITLE
Have any other datastest been tested? 

### ISSUE THREAD

**Issue by gmt710** [mikwieczorek/centroids-reid#14]
Thank you very much for your work on reid. 
I have reproduced your work and it looks very good.
But I would like to ask, have you tested it on other datasets? For example MSMT17.

**Comment by YDayoub** [comment]
@gmt710 
Hello, I ran the code with the provided trained model weights following the Test section structures. However, I am getting better results from the reported in the paper, I am getting 
  top-k, Rank-1  :98.5%
  top-k, Rank-5  :99.1%
  top-k, Rank-10 :99.6%
  top-k, Rank-20 :99.7%
  top-k, Rank-50 :99.9%
  mAP: 0.9873608809302383
  Could you tell me the results you got when you tried to reproduce the work?
  Thanks

**Comment by gmt710** [comment]
@YDayoub , Hello, Of course. you can find my result in [my blog](https://blog.csdn.net/qq_35975447/article/details/122849816?spm=1001.2014.3001.5501).

**Comment by YDayoub** [comment]
@gmt710
Thanks, I am getting different outputs 😐. I will look into it

**Comment by mikwieczorek** [comment]
Hi, @gmt710. No, we haven't tested our model with other datasets than those listed in the paper. I believe it should perform reasonably well with other ReID tasks, such as Vehicle ReID.

**Comment by gmt710** [comment]
Okay, I know. Thx.
