### ISSUE TITLE
Issue in running model for Street2Shop dataset

### ISSUE THREAD

**Issue by anushkajj** [mikwieczorek/centroids-reid#17]
Thank you for the scripts to convert Street2Shop annotations to COCO format. 
On running the scripts, although I am getting the number of images in 'gallery' as 0 for every category, and all available test images are  'user images'. Could you please confirm the numbers of the gallery images obtained?

**Comment by mikwieczorek** [comment]
There was a small bug, which may have caused the trouble. Now, it should be fixed.
Please make sure that you use proper paths to `meta` dir and the image folder with images in `jpg` format.
