### ISSUE TITLE
KeyError: 'state_dict'

### ISSUE THREAD

**Issue by masa8** [mikwieczorek/centroids-reid#36]
I put models in models folder and market1501 in data folder then run a following command.

```bash
python3 train_ctl_model.py TEST.ONLY_TEST True MODEL.PRETRAIN_PATH "./models/resnet50-19c8e357.pth" DATASETS.ROOT_DIR ./data
```
then, I got KeyError: 'state_dict' error.

```
Traceback (most recent call last):
  File "train_ctl_model.py", line 202, in <module>
    run_main(cfg, CTLModel, logger_save_dir)
  File "/app/utils/misc.py", line 183, in run_main
    run_single(cfg, method, logger_save_dir)
  File "/app/utils/misc.py", line 138, in run_single
    use_multiple_loggers=True if len(loggers) > 1 else False,
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/core/saving.py", line 158, in load_from_checkpoint
    model = cls._load_model_state(checkpoint, strict=strict, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/core/saving.py", line 204, in _load_model_state
    model.load_state_dict(checkpoint['state_dict'], strict=strict)
KeyError: 'state_dict'
```
It seems there is no `state_dict` in r50_ibn_a.pth and resnet50-19c8e357.pth also.

How can I load the models?

**Comment by masa8** [comment]
I may have misunderstood something.
What I wanted to do was to run inferences on a learned model.
In this case, maybe I should run steps describe [here](https://github.com/mikwieczorek/centroids-reid/tree/main/inference) instead of running `train_ctl_model.py` with TEST.ONLY_TEST True

So, I downloaded .ckpt from [here](https://drive.google.com/drive/folders/1NWD2Q0JGasGm9HTcOy4ZqsIqK4-IfknK)

and run a following command to get` embeddings.npy` I guess it's features
```
python3 inference/create_embeddings.py --config_file="configs/256_resnet50.yml" DATASETS.ROOT_DIR './data/market1501/bounding_box_train/' TEST.IMS_PER_BATCH 1 OUTPUT_DIR '.' TEST.ONLY_TEST True MODEL.PRETRAIN_PATH './models/market1501_resnet50_256_128_epoch_120.ckpt'
```
then, get similarity by following command.
```
python3 inference/get_similar.py --config_file="configs/320_resnet50_ibn_a.yml" --gallery_data='.' --normalize_features --topk=10 DATASETS.ROOT_DIR './data/market1501/query/' TEST.IMS_PER_BATCH 1 OUTPUT_DIR 'output-dir' TEST.ONLY_TEST True MODEL.PRETRAIN_PATH './models/market1501_resnet50_256_128_epoch_120.ckpt'  SOLVER.DISTANCE_FUNC 'cosine'
```
and then I got `query_embeddings.npy` `query_paths.npy` ` results.npy in `output-dir`
So far I don't know what that is, but I was able to load the model。

**Comment by blessedDS** [comment]
> I put models in models folder and market1501 in data folder then run a following command.
> 
> ```shell
> python3 train_ctl_model.py TEST.ONLY_TEST True MODEL.PRETRAIN_PATH "./models/resnet50-19c8e357.pth" DATASETS.ROOT_DIR ./data
> ```
> 
> then, I got KeyError: 'state_dict' error.
> 
> ```
> Traceback (most recent call last):
>   File "train_ctl_model.py", line 202, in <module>
>     run_main(cfg, CTLModel, logger_save_dir)
>   File "/app/utils/misc.py", line 183, in run_main
>     run_single(cfg, method, logger_save_dir)
>   File "/app/utils/misc.py", line 138, in run_single
>     use_multiple_loggers=True if len(loggers) > 1 else False,
>   File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/core/saving.py", line 158, in load_from_checkpoint
>     model = cls._load_model_state(checkpoint, strict=strict, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/core/saving.py", line 204, in _load_model_state
>     model.load_state_dict(checkpoint['state_dict'], strict=strict)
> KeyError: 'state_dict'
> ```
> 
> It seems there is no `state_dict` in r50_ibn_a.pth and resnet50-19c8e357.pth also.
> 
> How can I load the models?

how did you solve this issue i got the same error
