### ISSUE TITLE
How to get the same result in Market1501 

### ISSUE THREAD

**Issue by guhay** [mikwieczorek/centroids-reid#5]

**Comment by petertran1811** [comment]
Dear @mikwieczorek, 

I am trying to reproduce the result from your pre-trained weight in Market1501 dataset. Following here are the results: 
top-k, Rank-1  :93.9%
top-k, Rank-5  :98.2%
top-k, Rank-10 :98.9%
top-k, Rank-20 :99.4%
top-k, Rank-50 :99.6%
mAP: 0.8538947533255574

It seems like lower than in the paper. I followed the instruction in the repo. Everything is smooth, except for some minor errors related to version. After seeing the results, I also encountered the error as below: 
AttributeError: 'Trainer' object has no attribute 'accelerator_backend'
Exception ignored in: <function tqdm.__del__ at 0x7f759a7614c0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tqdm/std.py", line 1152, in __del__
  File "/usr/local/lib/python3.8/dist-packages/tqdm/std.py", line 1306, in close
  File "/usr/local/lib/python3.8/dist-packages/tqdm/std.py", line 1499, in display
  File "/usr/local/lib/python3.8/dist-packages/tqdm/std.py", line 1155, in __str__
  File "/usr/local/lib/python3.8/dist-packages/tqdm/std.py", line 1457, in format_dict
TypeError: cannot unpack non-iterable NoneType object

Do you have any advice for me regarding to this case? I am still trying to get the same result as you indicated. Hopefully I can have your opinion. Thank you in advance!

**Comment by mikwieczorek** [comment]
Hi @petertran1811,

The results you posted here are the results without using centroids for evaluation. If you run the test as stated in the Readme file, there are two evaluations happening. 1) stage uses no-centroids evaluation and it gives the results you provided. 2) stage using centroids for evaluation and this should give the results from the paper.

If you encountered the Error the 2nd stage did not start probably. 

You can run centroids evaluation directly adding `MODEL.USE_CENTROIDS True` to the command you used.

**Comment by gmt710** [comment]
@petertran1811 Hello, have you tried?

**Comment by gmt710** [comment]
The result is same with the [website](https://paperswithcode.com/sota/person-re-identification-on-market-1501).
