### ISSUE TITLE
Problem with running your codes in the colab space

### ISSUE THREAD

**Issue by ali-sobhani** [mikwieczorek/centroids-reid#7]
I try to run your codes with your instruction in the colab; but unfortunately, I see many bugs in running. The main error is coming from pytorch_lightning that in your custom version return this error:

`from torchtext._torchtext import (
ImportError: /usr/local/lib/python3.7/dist-packages/torchtext/_torchtext.so: undefined symbol: _ZNK3c104Type14isSubtypeOfExtERKSt10shared_ptrIS0_EPSo`

After changing many versions of your requirements and solving last error; Finally I receive this error:

`TypeError: __init__() got an unexpected keyword argument 'enable_pl_optimizer'`

Please check your codes in colab, and if it's possible for you, share your correct codes in the colab env.
thanks

**Comment by NBerlin** [comment]
For the initial error of torchtext I just uninstalled torchtext with `pip3 uninstall torchtext`

For the second error I installed Pytorch lightning v.1.1.4 through their Github with `pip3 install git+https://github.com/PyTorchLightning/pytorch-lightning@1.1.4`

Let me know if that helps in any way

**Comment by ali-sobhani** [comment]
Thanks for your answers @NBerlin, Your solution worked for me.
