### ISSUE TITLE
Can it run on windows？

### ISSUE THREAD

**Issue by CynicalHeart** [mikwieczorek/centroids-reid#8]
How can I not use the distributed training... 

The problem comes from Pytorch Lighting👇

_C.SOLVER.DIST_BACKEND="..."
- dp:  OSError[WinError 1455] The page file is too small to complete the operation;
- ddp: RuntimeError ：Distributed package doesn't have NCCL build in;
- ddp2: KeyError:'LOCAL_RANK';
- ddp_spawn: EOFError：Ran out of input;

I try to change NUM_WORK to `0` and batch to 32，but nothing changes. Does the program have to run on a linux os？

**Comment by mikwieczorek** [comment]
I am not using Windows on a daily basis, so I am not sure what can be wrong. Looks like a problem with NCCL, which may be related to PyTorch version. https://pytorch.org/docs/stable/distributed.html
Sorry, I am afraid I am not able to help a lot with running it on Windows.
