### ISSUE TITLE
running example

### ISSUE THREAD

**Issue by TranThanh96** [mikwieczorek/centroids-reid#9]
can you provide an example to run?
Can I use features at line code 59 in file "train_ctl_model.py" as a embedding vector ?

**Comment by mikwieczorek** [comment]
Yes, you can use the features from the line 59 in `train_ctl_model.py` as an embedding vector. Additionally, you can normalize the vector as in `utils/reid_metric.py` line 116. Of course both query and gallery embeddings should be normalized.

**Comment by mikwieczorek** [comment]
Added `inference` folder should now be easier to run as example

**Comment by TranThanh96** [comment]
thank you, close post
